package com.ignitionentertainment.dao;
// Generated 09-dic-2015 23:36:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Challenge generated by hbm2java
 */
public class Challenge  implements java.io.Serializable {


     private int id;
     private Date creationTime;
     private String name;
     private Integer numParticipants;
     private Integer idState;
     private Integer idLocation;
     private Date closingTime;
     private Date challengeTime;
     private String comments;
     private Integer idCreator;
     private Date modificationTime;

    public Challenge() {
    }

	
    public Challenge(int id) {
        this.id = id;
    }


	public Challenge(int id, Date creationTime, String name, Integer numParticipants, Integer idState,
			Integer idLocation, Date closingTime, Date challengeTime, String comments, Integer idCreator,
			Date modificationTime) {
		this.id = id;
		this.creationTime = creationTime;
		this.name = name;
		this.numParticipants = numParticipants;
		this.idState = idState;
		this.idLocation = idLocation;
		this.closingTime = closingTime;
		this.challengeTime = challengeTime;
		this.comments = comments;
		this.idCreator = idCreator;
		this.modificationTime = modificationTime;
	}


	public int getId() {
		return id;
	}


	public void setId(int id) {
		this.id = id;
	}


	public Date getCreationTime() {
		return creationTime;
	}


	public void setCreationTime(Date creationTime) {
		this.creationTime = creationTime;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public Integer getNumParticipants() {
		return numParticipants;
	}


	public void setNumParticipants(Integer numParticipants) {
		this.numParticipants = numParticipants;
	}


	public Integer getIdState() {
		return idState;
	}


	public void setIdState(Integer idState) {
		this.idState = idState;
	}


	public Integer getIdLocation() {
		return idLocation;
	}


	public void setIdLocation(Integer idLocation) {
		this.idLocation = idLocation;
	}


	public Date getClosingTime() {
		return closingTime;
	}


	public void setClosingTime(Date closingTime) {
		this.closingTime = closingTime;
	}


	public Date getChallengeTime() {
		return challengeTime;
	}


	public void setChallengeTime(Date challengeTime) {
		this.challengeTime = challengeTime;
	}


	public String getComments() {
		return comments;
	}


	public void setComments(String comments) {
		this.comments = comments;
	}


	public Integer getIdCreator() {
		return idCreator;
	}


	public void setIdCreator(Integer idCreator) {
		this.idCreator = idCreator;
	}


	public Date getModificationTime() {
		return modificationTime;
	}


	public void setModificationTime(Date modificationTime) {
		this.modificationTime = modificationTime;
	}

	public static class ChallengeBuilder {
		private int id;
	    private Date creationTime;
	    private String name;
	    private Integer numParticipants;
	    private Integer idState;
	    private Integer idLocation;
	    private Date closingTime;
	    private Date challengeTime;
	    private String comments;
	    private Integer idCreator;
	    private Date modificationTime;

    	public ChallengeBuilder(){
    	}
       
    	public ChallengeBuilder setId(int id) {
    		this.id = id;
    		return this;
    	}
    	
    	public ChallengeBuilder setCreationTime(Date creationTime) {
    		this.creationTime = creationTime;
    		return this;
    	}
    	
    	public ChallengeBuilder setName(String name) {
    		this.name = name;
    		return this;
    	}
    	
    	public ChallengeBuilder setNumParticipants(Integer numParticipants) {
    		this.numParticipants = numParticipants;
    		return this;
    	}
    	
    	public ChallengeBuilder setIdState(Integer idState) {
    		this.idState = idState;
    		return this;
    	}
    	
    	public ChallengeBuilder setIdLocation(Integer idLocation) {
    		this.idLocation = idLocation;
    		return this;
    	}
    	
    	public ChallengeBuilder setClosingTime(Date closingTime) {
    		this.closingTime = closingTime;
    		return this;
    	}
    	
    	public ChallengeBuilder setChallengeTime(Date challengeTime) {
    		this.challengeTime = challengeTime;
    		return this;
    	}
    	
    	public ChallengeBuilder setComments(String comments) {
    		this.comments = comments;
    		return this;
    	}
    	
    	public ChallengeBuilder setIdCreator(Integer idCreator) {
    		this.idCreator = idCreator;
    		return this;
    	}
    	
    	public ChallengeBuilder setModificationTime(Date modificationTime) {
    		this.modificationTime = modificationTime;
    		return this;
    	}
    	
    	public Challenge Build() {
    		return new Challenge(id, creationTime, name, numParticipants, idState,
    				idLocation, closingTime, challengeTime, comments, idCreator,
    				modificationTime);
    	}
    }
    

}


