package com.ignitionentertainment.dao;
// Generated 09-dic-2015 23:36:54 by Hibernate Tools 4.3.1

/**
 * ChallengeTag generated by hbm2java
 */
public class ChallengeTag  implements java.io.Serializable {


     private int id;
     private Integer idChallenge;
     private Integer idTag;

    public ChallengeTag() {
    }

	public ChallengeTag(int id, Integer idChallenge, Integer idTag) {
		this.id = id;
		this.idChallenge = idChallenge;
		this.idTag = idTag;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdChallenge() {
		return idChallenge;
	}

	public void setIdChallenge(Integer idChallenge) {
		this.idChallenge = idChallenge;
	}

	public Integer getIdTag() {
		return idTag;
	}

	public void setIdTag(Integer idTag) {
		this.idTag = idTag;
	}

    public static class ChallengeTagBuilder {
    	private int id;
        private Integer idChallenge;
        private Integer idTag;

    	public ChallengeTagBuilder(){
    	}
       
    	public ChallengeTagBuilder setId(int id) {
    		this.id = id;
    		return this;
    	}
    	
    	public ChallengeTagBuilder setIdChallenge(Integer idChallenge) {
    		this.idChallenge = idChallenge;
    		return this;
    	}
    	
    	public ChallengeTagBuilder setIdTag(Integer idTag) {
    		this.idTag = idTag;
    		return this;
    	}
    	
    	public ChallengeTag Build() {
    		return new ChallengeTag(id, idChallenge, idTag);
    	}
    }

}


