package com.ignitionentertainment.dao;
// Generated 09-dic-2015 23:36:54 by Hibernate Tools 4.3.1

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int id;
     private Double longitude;
     private Double latitude;

    public Location() {
    }

	
    public Location(int id) {
        this.id = id;
    }
    public Location(int id, Double longitude, Double latitude) {
       this.id = id;
       this.longitude = longitude;
       this.latitude = latitude;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public static class LocationBuilder {
    	private int id;
        private Double longitude;
        private Double latitude;

    	public LocationBuilder(){
    	}
       
    	public LocationBuilder setId(int id) {
    		this.id = id;
    		return this;
    	}
    	
    	public LocationBuilder setLongitude(Double longitude) {
    		this.longitude = longitude;
    		return this;
    	}
    	
    	public LocationBuilder setLatitude(Double latitude) {
    		this.latitude = latitude;
    		return this;
    	}
    	
    	public Location Build() {
    		return new Location(id, longitude, latitude);
    	}
    }
    
}


