package com.ignitionentertainment.dao;
// Generated 09-dic-2015 23:36:54 by Hibernate Tools 4.3.1

/**
 * Score generated by hbm2java
 */
public class Score  implements java.io.Serializable {


     private int id;
     private Integer wonChallenges;
     private Integer lostChallenges;
     private Integer totalChallenges;
     private Integer totalScore;

    public Score() {
    }

	
    public Score(int id) {
        this.id = id;
    }
    public Score(int id, Integer wonChallenges, Integer lostChallenges, Integer totalChallenges, Integer totalScore) {
       this.id = id;
       this.wonChallenges = wonChallenges;
       this.lostChallenges = lostChallenges;
       this.totalChallenges = totalChallenges;
       this.totalScore = totalScore;
    }
    
    public void init(){
    	this.wonChallenges = 0;
        this.lostChallenges = 0;
        this.totalChallenges = 0;
        this.totalScore = 0;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getWonChallenges() {
        return this.wonChallenges;
    }
    
    public void setWonChallenges(Integer wonChallenges) {
        this.wonChallenges = wonChallenges;
    }
    public Integer getLostChallenges() {
        return this.lostChallenges;
    }
    
    public void setLostChallenges(Integer lostChallenges) {
        this.lostChallenges = lostChallenges;
    }
    public Integer getTotalChallenges() {
        return this.totalChallenges;
    }
    
    public void setTotalChallenges(Integer totalChallenges) {
        this.totalChallenges = totalChallenges;
    }
    public Integer getTotalScore() {
        return this.totalScore;
    }
    
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    public void addLostChallenge() {
    	this.lostChallenges += 1;
    }
    
    public void addWonChallenge() {
    	this.wonChallenges += 1;
    }
    
    public void addTotalChallenge() {
    	this.totalChallenges += 1;
    }
    
    public void addTotalScore(int score) {
    	this.totalScore += score;
    }
    
    public static class ScoreBuilder {
    	private int id;
        private Integer wonChallenges;
        private Integer lostChallenges;
        private Integer totalChallenges;
        private Integer totalScore;

    	public ScoreBuilder(){
    	}
       
    	public ScoreBuilder setId(int id) {
    		this.id = id;
    		return this;
    	}
    	
    	public ScoreBuilder setWonChallenges(Integer wonChallenges) {
    		this.wonChallenges = wonChallenges;
    		return this;
    	}
    	
    	public ScoreBuilder setLostChallenges(Integer lostChallenges) {
    		this.lostChallenges = lostChallenges;
    		return this;
    	}
    	
    	public ScoreBuilder setTotalChallenges(Integer totalChallenges) {
    		this.totalChallenges = totalChallenges;
    		return this;
    	}
    	
    	public ScoreBuilder setTotalScore(Integer totalScore) {
    		this.totalScore = totalScore;
    		return this;
    	}
    	
    	public Score Build() {
    		return new Score(id, wonChallenges, lostChallenges, totalChallenges, totalScore);
    	}
    }
}


