package com.ignitionentertainment.dao;
// Generated 09-dic-2015 23:36:54 by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String username;
     private String email;
     private String password;
     private Integer idAvatar;
     private Integer idScore;
     private Integer idLocation;

    public User() {
    }
    
    public User(int id, String username, String email, String password, Integer idAvatar, Integer idScore, Integer idLocation) {
       this.id = id;
       this.username = username;
       this.email = email;
       this.password = password;
       this.idAvatar = idAvatar;
       this.idScore = idScore;
       this.idLocation = idLocation;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername(){
    	return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getIdAvatar() {
        return this.idAvatar;
    }
    
    public void setIdAvatar(Integer idAvatar) {
        this.idAvatar = idAvatar;
    }
    public Integer getIdScore() {
        return this.idScore;
    }
    
    public void setIdScore(Integer idScore) {
        this.idScore = idScore;
    }
    public Integer getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Integer idLocation) {
        this.idLocation = idLocation;
    }

    public static class UserBuilder {
    	private int id;
        private String username;
        private String email;
        private String password;
        private Integer idAvatar;
        private Integer idScore;
        private Integer idLocation;

    	public UserBuilder(){
    	}
       
    	public UserBuilder setId(int id) {
    		this.id = id;
    		return this;
    	}
    	
    	public UserBuilder setUsername(String username) {
    		this.username = username;
    		return this;
    	}
    	
    	public UserBuilder setEmail(String email) {
    		this.email = email;
    		return this;
    	}
    	
    	public UserBuilder setPassword(String password) {
    		this.password = password;
    		return this;
    	}
    	
    	public UserBuilder setIdAvatar(Integer idAvatar) {
    		this.idAvatar = idAvatar;
    		return this;
    	}
    	
    	public UserBuilder setIdScore(Integer idScore) {
    		this.idScore = idScore;
    		return this;
    	}
    	
    	public UserBuilder setIdLocation(Integer idLocation) {
    		this.idLocation = idLocation;
    		return this;
    	}
    	
    	public User Build() {
    		return new User(id, username, email, password, idAvatar, idScore, idLocation);
    	}
    }


}


